default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: validation_study_development

test:
  <<: *default
  database: validation_study_test

production:
  <<: *default
  database: validation_study_production
